// <auto-generated />
using System;
using AnimalShelterAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelterAPI.Migrations
{
    [DbContext(typeof(AnimalShelterAPIContext))]
    [Migration("20220910214119_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AnimalShelterAPI.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("Adopted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("AdoptionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Age")
                        .HasColumnType("double");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Coloring")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25) CHARACTER SET utf8mb4");

                    b.Property<int>("Personality")
                        .HasColumnType("int");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("double");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            About = "Love Cheek and Chin Scratches!",
                            Adopted = false,
                            AdoptionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Age = 2.0,
                            Breed = "Domestic Medium Hair",
                            Coloring = "Black",
                            Name = "Domino",
                            Personality = 3,
                            Sex = 0,
                            Type = 0,
                            Weight = 11.800000000000001
                        },
                        new
                        {
                            AnimalId = 2,
                            About = "Always PURRing and PURRfect!",
                            Adopted = false,
                            AdoptionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Age = 0.29999999999999999,
                            Breed = "Domestic Short Hair",
                            Coloring = "Brown Tabby",
                            Name = "Doug",
                            Personality = 4,
                            Sex = 0,
                            Type = 0,
                            Weight = 5.2000000000000002
                        },
                        new
                        {
                            AnimalId = 3,
                            About = "Anxious around new animals and people, but very sweet!",
                            Adopted = false,
                            AdoptionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Age = 2.0,
                            Breed = "Domestic Short Hair",
                            Coloring = "Blue Tabby",
                            Name = "Bunny",
                            Personality = 5,
                            Sex = 0,
                            Type = 0,
                            Weight = 7.4000000000000004
                        },
                        new
                        {
                            AnimalId = 4,
                            About = "Playful biter, loves chassing rabbits!",
                            Adopted = false,
                            AdoptionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Age = 7.0,
                            Breed = "Labrador",
                            Coloring = "Yellow",
                            Name = "Angus",
                            Personality = 6,
                            Sex = 0,
                            Type = 1,
                            Weight = 101.3
                        },
                        new
                        {
                            AnimalId = 5,
                            About = "A true HomeBuddy! Knows many tricks and is a quick learner!",
                            Adopted = false,
                            AdoptionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Age = 1.8999999999999999,
                            Breed = "American Pit Bull - Australian Shepherd",
                            Coloring = "White Brown",
                            Name = "Penny",
                            Personality = 1,
                            Sex = 1,
                            Type = 1,
                            Weight = 52.100000000000001
                        },
                        new
                        {
                            AnimalId = 6,
                            About = "Love to Learn and Love to Cuddle!",
                            Adopted = false,
                            AdoptionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Age = 1.5,
                            Breed = "Dachsund",
                            Coloring = "Red White",
                            Name = "Churro",
                            Personality = 0,
                            Sex = 0,
                            Type = 1,
                            Weight = 15.0
                        },
                        new
                        {
                            AnimalId = 7,
                            About = "Fun fun fun!",
                            Adopted = false,
                            AdoptionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Age = 3.0,
                            Breed = "Cattle",
                            Coloring = "Black White",
                            Name = "Milo",
                            Personality = 7,
                            Sex = 1,
                            Type = 1,
                            Weight = 50.0
                        },
                        new
                        {
                            AnimalId = 8,
                            About = "Wild heart!",
                            Adopted = false,
                            AdoptionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Age = 5.0,
                            Breed = "Calico",
                            Coloring = "Black White Orange",
                            Name = "Mitsy",
                            Personality = 0,
                            Sex = 1,
                            Type = 0,
                            Weight = 15.0
                        },
                        new
                        {
                            AnimalId = 9,
                            About = "I love to explore!",
                            Adopted = false,
                            AdoptionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Age = 7.0,
                            Breed = "Hound",
                            Coloring = "Brown White",
                            Name = "Brutus",
                            Personality = 6,
                            Sex = 0,
                            Type = 1,
                            Weight = 75.0
                        },
                        new
                        {
                            AnimalId = 10,
                            About = "Follow my leader!",
                            Adopted = false,
                            AdoptionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Age = 8.0,
                            Breed = "Collie",
                            Coloring = "Black Tan",
                            Name = "Baron",
                            Personality = 3,
                            Sex = 0,
                            Type = 1,
                            Weight = 55.0
                        },
                        new
                        {
                            AnimalId = 11,
                            About = "Lets play!",
                            Adopted = false,
                            AdoptionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Age = 1.5,
                            Breed = "Mix",
                            Coloring = "Golden",
                            Name = "Brew",
                            Personality = 2,
                            Sex = 1,
                            Type = 1,
                            Weight = 35.0
                        },
                        new
                        {
                            AnimalId = 12,
                            About = "Shop cat!",
                            Adopted = false,
                            AdoptionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Age = 5.0,
                            Breed = "Tabby",
                            Coloring = "Brown Grey",
                            Name = "Midge",
                            Personality = 1,
                            Sex = 0,
                            Type = 0,
                            Weight = 22.0
                        },
                        new
                        {
                            AnimalId = 13,
                            About = "Throw the ball please!",
                            Adopted = false,
                            AdoptionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Age = 6.5,
                            Breed = "Chow",
                            Coloring = "Grey",
                            Name = "Chubs",
                            Personality = 4,
                            Sex = 0,
                            Type = 1,
                            Weight = 65.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
